-- Apaga as tabelas existentes na ordem inversa de dependência para evitar erros.
-- Use com cuidado, pois isso deletará todos os dados.
DROP TABLE IF EXISTS roteiros;
DROP TABLE IF EXISTS canais;
DROP TABLE IF EXISTS vozes;
DROP TABLE IF EXISTS apis;

-- Tabela para armazenar chaves de API de diferentes serviços.
CREATE TABLE public.apis (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plataforma TEXT NOT NULL DEFAULT '',
    api_key TEXT NOT NULL DEFAULT '',
    group_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabela para armazenar as vozes disponíveis para narração.
CREATE TABLE public.vozes (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_voz TEXT NOT NULL DEFAULT '',
    voice_id TEXT NOT NULL DEFAULT '',
    plataforma TEXT,
    idioma TEXT NOT NULL DEFAULT '',
    genero TEXT NOT NULL DEFAULT '',
    preview_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabela para configurar os diferentes canais de conteúdo.
CREATE TABLE public.canais (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_canal TEXT NOT NULL DEFAULT '',
    prompt_roteiro TEXT,
    prompt_titulo TEXT,
    prompt_thumb TEXT,
    voz_preferida_id INT,
    media_chars NUMERIC(10, 2), -- Exemplo: precisão de 10 dígitos, com 2 casas decimais.
    roteiro_1 TEXT,
    roteiro_2 TEXT,
    roteiro_3 TEXT,
    titulo_1 TEXT,
    titulo_2 TEXT,
    titulo_3 TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Define a chave estrangeira para a voz preferida.
    CONSTRAINT canais_voz_preferida_id_fkey FOREIGN KEY (voz_preferida_id)
        REFERENCES vozes(id)
        ON DELETE SET NULL -- Se uma voz for deletada, este campo ficará nulo.
);

-- Tabela principal para os roteiros gerados, associados a um canal.
CREATE TABLE public.roteiros (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    canal_id INT NOT NULL,
    roteiro TEXT NOT NULL,
    titulo TEXT,
    audio_path TEXT,
    text_thumb TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Define a chave estrangeira para o canal.
    CONSTRAINT roteiros_canal_id_fkey FOREIGN KEY (canal_id)
        REFERENCES canais(id)
        ON DELETE CASCADE -- Se um canal for deletado, seus roteiros também serão.
);

-- CRIAÇÃO DE ÍNDICES PARA OTIMIZAÇÃO --
-- Índices em chaves estrangeiras aceleram muito as operações de JOIN.
CREATE INDEX ON public.canais (voz_preferida_id);
CREATE INDEX ON public.roteiros (canal_id);
